version: "3.8"
services:
  alphabot:
    build: .
    volumes:
      - .:/app
    command: bash -c "cd /app && python3 -u bot.py"
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 50M
        reservations:
          cpus: "0.25"
          memory: 20M 

